# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

before_install:
 - gem install cocoapods
 - pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Hashtags.xcworkspace -scheme Hashtags-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
